import { useState, useMemo } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { ScrollArea } from '@/components/ui/scroll-area'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Separator } from '@/components/ui/separator'
import type { KnowledgeArticle } from '@/lib/knowledge-base'
import { searchKnowledgeBase, getKnowledgeBaseStats, rateArticle, incrementArticleView } from '@/lib/knowledge-base'
import { Book, MagnifyingGlass, ThumbsUp, ThumbsDown, Eye, Sparkle, Tag, ChartBar } from '@phosphor-icons/react'
import { formatDate } from '@/lib/utils'

interface KnowledgeBaseProps {
  articles: KnowledgeArticle[]
  onArticleRate: (articleId: string, helpful: boolean) => void
  onArticleView: (articleId: string) => void
}

export function KnowledgeBase({ articles, onArticleRate, onArticleView }: KnowledgeBaseProps) {
  const [searchQuery, setSearchQuery] = useState('')
  const [selectedCategory, setSelectedCategory] = useState<string>('all')
  const [selectedArticle, setSelectedArticle] = useState<KnowledgeArticle | null>(null)

  const filteredArticles = useMemo(() => {
    const categoryFilter = selectedCategory === 'all' ? undefined : selectedCategory
    return searchKnowledgeBase(articles, searchQuery, {
      category: categoryFilter
    })
  }, [articles, searchQuery, selectedCategory])

  const stats = useMemo(() => getKnowledgeBaseStats(articles), [articles])

  const categories = ['all', 'incident', 'solution', 'procedure', 'troubleshooting', 'best-practice']

  const handleArticleClick = (article: KnowledgeArticle) => {
    setSelectedArticle(article)
    onArticleView(article.id)
  }

  const handleRate = (helpful: boolean) => {
    if (selectedArticle) {
      onArticleRate(selectedArticle.id, helpful)
      setSelectedArticle({
        ...selectedArticle,
        helpful: helpful ? selectedArticle.helpful + 1 : selectedArticle.helpful,
        notHelpful: !helpful ? selectedArticle.notHelpful + 1 : selectedArticle.notHelpful
      })
    }
  }

  return (
    <>
      <div className="space-y-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Book size={24} weight="duotone" className="text-primary" />
              Knowledge Base
            </CardTitle>
            <CardDescription>
              Searchable repository of incident solutions and best practices
            </CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
              <div className="p-4 rounded-lg border bg-card">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-muted-foreground">Total Articles</span>
                  <Book size={20} weight="duotone" className="text-primary" />
                </div>
                <div className="text-3xl font-bold">{stats.totalArticles}</div>
              </div>

              <div className="p-4 rounded-lg border bg-card">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-muted-foreground">Auto-Generated</span>
                  <Sparkle size={20} weight="duotone" className="text-accent" />
                </div>
                <div className="text-3xl font-bold text-accent">{stats.autoGeneratedArticles}</div>
              </div>

              <div className="p-4 rounded-lg border bg-card">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-muted-foreground">Total Views</span>
                  <Eye size={20} weight="duotone" className="text-muted-foreground" />
                </div>
                <div className="text-3xl font-bold">{stats.totalViews}</div>
              </div>

              <div className="p-4 rounded-lg border bg-card">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-sm text-muted-foreground">Avg Helpfulness</span>
                  <ChartBar size={20} weight="duotone" className="text-success" />
                </div>
                <div className="text-3xl font-bold text-success">
                  {stats.averageHelpfulness.toFixed(0)}%
                </div>
              </div>
            </div>

            <div className="flex gap-4 mb-4">
              <div className="flex-1 relative">
                <MagnifyingGlass
                  size={20}
                  className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground"
                  weight="duotone"
                />
                <Input
                  placeholder="Search knowledge base..."
                  value={searchQuery}
                  onChange={e => setSearchQuery(e.target.value)}
                  className="pl-10"
                />
              </div>
            </div>

            <Tabs value={selectedCategory} onValueChange={setSelectedCategory} className="space-y-4">
              <TabsList className="grid w-full grid-cols-6">
                {categories.map(cat => (
                  <TabsTrigger key={cat} value={cat}>
                    {cat.charAt(0).toUpperCase() + cat.slice(1)}
                    {cat !== 'all' && stats.articlesByCategory[cat] && (
                      <Badge variant="secondary" className="ml-2">
                        {stats.articlesByCategory[cat]}
                      </Badge>
                    )}
                  </TabsTrigger>
                ))}
              </TabsList>

              <TabsContent value={selectedCategory} className="space-y-3">
                <ScrollArea className="h-[500px]">
                  {filteredArticles.length === 0 ? (
                    <Alert>
                      <AlertDescription>
                        No articles found matching your search criteria.
                      </AlertDescription>
                    </Alert>
                  ) : (
                    <div className="space-y-3">
                      {filteredArticles.map(article => (
                        <ArticleCard
                          key={article.id}
                          article={article}
                          onClick={() => handleArticleClick(article)}
                        />
                      ))}
                    </div>
                  )}
                </ScrollArea>
              </TabsContent>
            </Tabs>
          </CardContent>
        </Card>
      </div>

      <Dialog open={selectedArticle !== null} onOpenChange={() => setSelectedArticle(null)}>
        <DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
          {selectedArticle && (
            <>
              <DialogHeader>
                <DialogTitle className="flex items-center gap-3">
                  {selectedArticle.title}
                  {selectedArticle.autoGenerated && (
                    <Badge variant="secondary" className="flex items-center gap-1">
                      <Sparkle size={14} weight="duotone" />
                      Auto-Generated
                    </Badge>
                  )}
                </DialogTitle>
                <DialogDescription>{selectedArticle.summary}</DialogDescription>
              </DialogHeader>

              <div className="space-y-6 py-4">
                <div className="flex flex-wrap gap-2">
                  {selectedArticle.tags.map(tag => (
                    <Badge key={tag} variant="outline" className="flex items-center gap-1">
                      <Tag size={12} weight="duotone" />
                      {tag}
                    </Badge>
                  ))}
                </div>

                <Separator />

                <div className="prose prose-sm max-w-none">
                  <div className="whitespace-pre-wrap text-sm leading-relaxed">
                    {selectedArticle.content}
                  </div>
                </div>

                <Separator />

                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-4 text-sm text-muted-foreground">
                    <div className="flex items-center gap-2">
                      <Eye size={16} weight="duotone" />
                      <span>{selectedArticle.views} views</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <ThumbsUp size={16} weight="duotone" />
                      <span>{selectedArticle.helpful} helpful</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <ThumbsDown size={16} weight="duotone" />
                      <span>{selectedArticle.notHelpful} not helpful</span>
                    </div>
                  </div>

                  <div className="text-xs text-muted-foreground">
                    Created {formatDate(selectedArticle.createdAt)} by {selectedArticle.createdBy}
                  </div>
                </div>

                <Separator />

                <div className="flex items-center justify-center gap-4">
                  <Button
                    onClick={() => handleRate(true)}
                    variant="outline"
                    size="lg"
                    className="flex items-center gap-2"
                  >
                    <ThumbsUp size={20} weight="duotone" />
                    Helpful
                  </Button>
                  <Button
                    onClick={() => handleRate(false)}
                    variant="outline"
                    size="lg"
                    className="flex items-center gap-2"
                  >
                    <ThumbsDown size={20} weight="duotone" />
                    Not Helpful
                  </Button>
                </div>
              </div>
            </>
          )}
        </DialogContent>
      </Dialog>
    </>
  )
}

interface ArticleCardProps {
  article: KnowledgeArticle
  onClick: () => void
}

function ArticleCard({ article, onClick }: ArticleCardProps) {
  const helpfulness = article.helpful + article.notHelpful > 0
    ? (article.helpful / (article.helpful + article.notHelpful)) * 100
    : 0

  return (
    <Card className="cursor-pointer hover:border-primary transition-colors" onClick={onClick}>
      <CardContent className="pt-6">
        <div className="space-y-3">
          <div className="flex items-start justify-between gap-4">
            <div className="flex-1">
              <h4 className="font-semibold flex items-center gap-2">
                {article.title}
                {article.autoGenerated && (
                  <Sparkle size={16} weight="duotone" className="text-accent" />
                )}
              </h4>
              <p className="text-sm text-muted-foreground mt-1 line-clamp-2">
                {article.summary}
              </p>
            </div>
            <Badge variant="secondary">{article.category}</Badge>
          </div>

          <div className="flex items-center justify-between">
            <div className="flex flex-wrap gap-2">
              {article.tags.slice(0, 3).map(tag => (
                <Badge key={tag} variant="outline" className="text-xs">
                  {tag}
                </Badge>
              ))}
              {article.tags.length > 3 && (
                <Badge variant="outline" className="text-xs">
                  +{article.tags.length - 3}
                </Badge>
              )}
            </div>

            <div className="flex items-center gap-3 text-xs text-muted-foreground">
              <div className="flex items-center gap-1">
                <Eye size={14} weight="duotone" />
                <span>{article.views}</span>
              </div>
              {article.helpful + article.notHelpful > 0 && (
                <div className="flex items-center gap-1">
                  <ThumbsUp size={14} weight="duotone" className={helpfulness >= 70 ? 'text-success' : ''} />
                  <span>{helpfulness.toFixed(0)}%</span>
                </div>
              )}
            </div>
          </div>
        </div>
      </CardContent>
    </Card>
  )
}
